import Head from "next/head";
import Header from "@/components/general/header";
import Frame from "@/components/general/frame";
import TestProfile from "@/assets/test_profile.jpg"
import Image from "next/image";
import Bg from "@/components/general/bg";

function Field({ fieldname, value, isList = false }){
  
  return(
    <div class="flex flex-col space-y-4">
      <span class="text-white text-sm">{fieldname}:</span>
      {
      isList? 
      value.map(v => <Frame class="text-white font-bold text-lg" spy={true}>{v}</Frame>) :
      <Frame class="text-white font-bold text-lg" spy={true}>{value}</Frame>
      }
    </div>
  );
}

export default function Home() {

  const testUser = {
    image: TestProfile,
    firstname:"Maximiliano",
    lastname:"Kallenbach",
    rol:"Dev",
    projects: ["Adelphi", "Prior"],
    food: "Milanesa Napo",
    hobbie: "Videojuegos",
    hair: "Marron",
    eyes: "Marron"
  }

  const user = testUser;
  
  return (
    <>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-black h-screen">
        <Bg>
          <Header />
          <div class="flex flex-row p-16 space-x-20 w-full h-full">
            <div class="flex flex-col w-1/3">
              <Frame>
                <Image src={user.image} class="rounded-xl w-[292px]"/>
              </Frame>
            </div>
            <div class="flex flex-col w-2/3 space-y-5">
              <div class=" text-5xl font-semibold">
                {user.firstname} {user.lastname}
              </div>
              <div class="flex flex-row">
                <div class="flex flex-col w-1/2 space-y-8">
                  <Field fieldname="Rol" value={user.rol}/>
                  <Field fieldname="Projects" value={user.projects} isList={true}/>
                </div>
                <div class="flex flex-col w-1/2 space-y-8">
                  <Field fieldname="Comida Favorita" value={user.food}/>
                  <Field fieldname="Hobbie" value={user.hobbie}/>
                  <Field fieldname="Color de pelo" value={user.hair}/>
                  <Field fieldname="Color de ojos" value={user.eyes}/>
                </div>
              </div>
            </div>
          </div>
        </Bg>
      </main>
    </>
  );
}
