import Head from "next/head";
import Header from "@/components/general/header";
import Frame from "@/components/general/frame";
import TestProfile from "@/assets/test_profile.jpg"
import Image from "next/image";
import Bg from "@/components/general/bg";
import Link from "next/link";
import ButtonZerf from "@/components/general/buttonZerf";

function Field({ fieldname, value, isList = false }){
  
  return(
    <div class="flex flex-col space-y-4">
      <span class="text-white text-sm">{fieldname}:</span>
      {
      isList? 
      value.map(v => <Frame class="text-white font-bold text-lg" spy={true}>{v}</Frame>) :
      <Frame class="text-white font-bold text-lg" spy={true}>{value}</Frame>
      }
    </div>
  );
}

function Card({children, href ="", title}){
return (
  <div class="w-3/4">
    <Frame wfull={true}>
      <div class="flex flex-col w-full p-3 space-y-3">
        <div class="flex flex-row justify-between">
          <span>{title}</span><Link href={href}>Editar</Link>
        </div>
        <div class="h-0.5 w-full bg-gray-500"/>
        <div class="grid grid-cols-2 w-full">
          {children}
        </div>
      </div>
    </Frame>
  </div>
);
}

export default function Home() {

  const testUser = {
    image: TestProfile,
    firstname:"Maximiliano",
    lastname:"Kallenbach",
    rol:"Dev",
    projects: ["Adelphi", "Prior"],
    food: "Milanesa Napo",
    hobbie: "Videojuegos",
    hair: "Marron",
    eyes: "Marron"
  }

  const user = testUser;
  
  return (
    <>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main class="bg-black h-screen">
        <Bg>
          <Header />
          <div class="flex flex-row p-16 space-x-20 w-full h-full overflow-hidden">
            <div class="flex flex-col w-1/3 space-y-4">
              <div class="flex flex-row w-full justify-center">
              <Frame>
                <Image src={user.image} class="rounded-xl w-[292px]"/>
              </Frame>
              </div>
              <div class="flex flex-row w-full justify-center">
              <ButtonZerf>Generar Zerfito</ButtonZerf>
              </div>
            </div>
            <div class="flex flex-col w-2/3 space-y-5">
              <div class=" text-5xl font-semibold">
                {user.firstname} {user.lastname}
              </div>
              <div class="flex flex-col w-full space-y-4 overflow-scroll p-2">
                <Card title={"Name"} href={"../../edit_profile?step=1"}>
                  <Field fieldname="Rol" value={user.rol}/>
                  <Field fieldname="Projects" value={user.projects} isList={true}/>
                </Card>
                <Card title={"Name"} href={"../../edit_profile?step=2"}>
                  <Field fieldname="Comida Favorita" value={user.food}/>
                  <Field fieldname="Hobbie" value={user.hobbie}/>
                </Card>
                <Card title={"Name"} href={"../../edit_profile?step=3"}>
                    <Field fieldname="Color de pelo" value={user.hair}/>
                    <Field fieldname="Color de ojos" value={user.eyes}/>
                </Card>
              </div>
            </div>
          </div>
        </Bg>
      </main>
    </>
  );
}
