import Counter from "@/components/counter";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Page Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex flex-col items-center justify-center w-full bg-gradient-to-tr from-zerf-contrast via-zerf/90 to-zerf text-white gap-4">
        <h1 className="text-3xl md:text-5xl lg:text-7xl font-bold">
          NextJS React Training
        </h1>
        <Counter />
      </main>
    </>
  );
}
